version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
     ports:
      - "8080:8080"
    env:
      BACKEND_PORT: 9000
      BACKEND_DNS: localhost
    depends_on:
      - backend
  
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    env:
      REDIS_DNS: blank

