version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
      BACKEND_PORT: 9000
      BACKEND_DNS: backend
    depends_on:
      - backend
  
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    # environment:
    #   REDIS_DNS: something here when we have redis

