# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: PR
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build backend
      run: go build -v ./backend

    - name: Test
      run: go test -v ./backend

    - name: Build frontend
      run: go build -v ./frontend

    - name: Test frontend
      run: go test -v ./frontend
